FORMAT: 1A
NOTE: This document is a **work in progress**.

# Group User

## Base [/api/user]

### List all users [GET]

+ Response 200 (application/json)

    + Body

            {
                "current_page": 1,
                "data": [
                    {
                        "id": 1,
                        "name": "Galho#1407",
                        "profile_photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                        "background_photo": "http:\/\/localhost:8000\/imgs\/background_photo.avif",
                        "about": "Nada informado",
                        "banned": false,
                        "message": true,
                        "report_message": true,
                        "report_chapter": true,
                        "create_manga": false,
                        "update_manga": false,
                        "delete_manga": false,
                        "upload_manga_chapter": false,
                        "update_manga_chapter": false,
                        "delete_manga_chapter": false,
                        "create_novel": false,
                        "update_novel": false,
                        "delete_novel": false,
                        "upload_novel_chapter": false,
                        "update_novel_chapter": false,
                        "delete_novel_chapter": false,
                        "create_people": false,
                        "update_people": false,
                        "delete_people": false,
                        "ban_user": false,
                        "unban_user": false,
                        "manager_permisions": false,
	                    "owner": false,
                        "created_at": "2022-03-13T01:57:31.000000Z",
                        "updated_at": "2022-03-13T01:57:31.000000Z"
                    }
                ],
                "first_page_url": "http:\/\/localhost:8000\/api\/user?page=1",
                "from": 1,
                "last_page": 1,
                "last_page_url": "http:\/\/localhost:8000\/api\/user?page=1",
                "links": [
                    {
                        "url": null,
                        "label": "&laquo; Previous",
                        "active": false
                    },
                    {
                        "url": "http:\/\/localhost:8000\/api\/user?page=1",
                        "label": "1",
                        "active": true
                    },
                    {
                        "url": null,
                        "label": "Next &raquo;",
                        "active": false
                    }
                ],
                "next_page_url": null,
                "path": "http:\/\/localhost:8000\/api\/user",
                "per_page": 20,
                "prev_page_url": null,
                "to": 1,
                "total": 1
            }

### Create user [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "name": "Galho",
                "email": "exemple@mail.com",
                "password": "passwordexemple"
            }


+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#1407",
                "profile_photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "background_photo": "http:\/\/localhost:8000\/imgs\/background_photo.avif",
                "about": "Nada informado",
                "banned": false,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": false,
                "update_manga": false,
                "delete_manga": false,
                "upload_manga_chapter": false,
                "update_manga_chapter": false,
                "delete_manga_chapter": false,
                "create_novel": false,
                "update_novel": false,
                "delete_novel": false,
                "upload_novel_chapter": false,
                "update_novel_chapter": false,
                "delete_novel_chapter": false,
                "create_people": false,
                "update_people": false,
                "delete_people": false,
                "ban_user": false,
                "unban_user": false,
                "manager_permisions": false,
	            "owner": false,
                "created_at": "2022-03-13T01:57:31.000000Z",
                "updated_at": "2022-03-13T01:57:31.000000Z",
                "token": "1|1zpcx0tElYTmrmtxuijh28yydCxyZA5m754SXp2I"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The email has already been taken.",
                "errors": {
                    "email": [
                        "The email has already been taken."
                    ]
                }
            }

### Delete user [DELETE]

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

+ Response 200

+ Response 500

+ Response 403

## Get User [/api/user/{name}/{tag}]

### Get user by name tag [GET]

+ Parameters

    + name: `Galho` (string)
    + tag: `1234` (string)

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#1721",
                "profile_photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "background_photo": "http:\/\/localhost:8000\/imgs\/background_photo.avif",
                "about": "Nada informado",
                "banned": false,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": false,
                "update_manga": false,
                "delete_manga": false,
                "upload_manga_chapter": false,
                "update_manga_chapter": false,
                "delete_manga_chapter": false,
                "create_novel": false,
                "update_novel": false,
                "delete_novel": false,
                "upload_novel_chapter": false,
                "update_novel_chapter": false,
                "delete_novel_chapter": false,
                "create_people": false,
                "update_people": false,
                "delete_people": false,
                "ban_user": false,
                "unban_user": false,
                "manager_permisions": false,
                "owner": false,
                "created_at": "2022-03-13T20:04:20.000000Z",
                "updated_at": "2022-03-13T20:04:20.000000Z"
            }

## Base2 [/api/user/update]

### Update user [POST]

+ Request (multipart/form-data)

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA
            Accept: application/json

    + Body

            name: "Galho" (String)
            tag: 1234 (4 number)
            about: "um animal desprovido da inteligencia" (String)
            profile_photo: image (image)
            background_photo: image (image)

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#1721",
                "profile_photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "background_photo": "http:\/\/localhost:8000\/imgs\/background_photo.avif",
                "about": "Nada informado",
                "banned": false,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": false,
                "update_manga": false,
                "delete_manga": false,
                "upload_manga_chapter": false,
                "update_manga_chapter": false,
                "delete_manga_chapter": false,
                "create_novel": false,
                "update_novel": false,
                "delete_novel": false,
                "upload_novel_chapter": false,
                "update_novel_chapter": false,
                "delete_novel_chapter": false,
                "create_people": false,
                "update_people": false,
                "delete_people": false,
                "ban_user": false,
                "unban_user": false,
                "manager_permisions": false,
                "owner": false,
                "created_at": "2022-03-13T20:04:20.000000Z",
                "updated_at": "2022-03-13T20:04:20.000000Z"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The tag must not be greater than 4 characters.",
                "errors": {
                    "tag": [
                        "The tag must not be greater than 4 characters."
                    ]
                }
            }

## Auth [/api/auth]

### Login [POST]

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "email": "exemple@mail.com",
                "password": "passwordexemple"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#1407",
                "profile_photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "background_photo": "http:\/\/localhost:8000\/imgs\/background_photo.avif",
                "about": "Nada informado",
                "banned": false,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": false,
                "update_manga": false,
                "delete_manga": false,
                "upload_manga_chapter": false,
                "update_manga_chapter": false,
                "delete_manga_chapter": false,
                "create_novel": false,
                "update_novel": false,
                "delete_novel": false,
                "upload_novel_chapter": false,
                "update_novel_chapter": false,
                "delete_novel_chapter": false,
                "create_people": false,
                "update_people": false,
                "delete_people": false,
                "ban_user": false,
                "unban_user": false,
                "manager_permisions": false,
	            "owner": false,
                "created_at": "2022-03-13T01:57:31.000000Z",
                "updated_at": "2022-03-13T01:57:31.000000Z",
                "token": "2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA"
            }

+ Response 404

+ Response 403

+ Response 422 (application/json)

    + Body

            {
                "message": "The password must be at least 8 characters.",
                "errors": {
                    "password": [
                        "The password must be at least 8 characters."
                    ]
                }
            }

### Logout [DELETE]

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

+ Response 200

+ Response 403

## Auth2 [/api/auth/{id}]

### Revoke token [DELETE]

+ Parameters
    + id: `2` (integer) token id

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

+ Response 200

+ Response 403

### Get logins [GET]

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

+ Response 200 (application/json)

        [
            {
                "id": 6,
                "tokenable_type": "App\\Models\\User",
                "tokenable_id": 4,
                "name": "insomnia\/2021.7.2",
                "abilities": [
                    "*"
                ],
                "last_used_at": "2022-03-13T19:02:12.000000Z",
                "created_at": "2022-03-13T18:46:35.000000Z",
                "updated_at": "2022-03-13T19:02:12.000000Z"
            },
            {
                "id": 8,
                "tokenable_type": "App\\Models\\User",
                "tokenable_id": 4,
                "name": "insomnia\/2021.7.2",
                "abilities": [
                    "*"
                ],
                "last_used_at": null,
                "created_at": "2022-03-13T18:47:45.000000Z",
                "updated_at": "2022-03-13T18:47:45.000000Z"
            }
        ]

+ Response 403

# Group Admin

## Manage permissions [/api/admin/user/{id}]

### Manage permissions [POST]

(manager_permisions requerid or owner)

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

    + Body

            message: 1 (Boolean)
            report_message: 1 (Boolean)
            report_chapter: 1 (Boolean)
            create_manga: 1 (Boolean)
            update_manga: 1 (Boolean)
            delete_manga: 1 (Boolean)
            upload_manga_chapter: 1 (Boolean)
            update_manga_chapter: 1 (Boolean)
            delete_manga_chapter: 1 (Boolean)
            create_novel: 1 (Boolean)
            update_novel: 1 (Boolean)
            delete_novel: 1 (Boolean)
            upload_novel_chapter: 1 (Boolean)
            update_novel_chapter: 1 (Boolean)
            delete_novel_chapter: 1 (Boolean)
            create_people: 1 (Boolean)
            update_people: 1 (Boolean)
            delete_people: 1 (Boolean)
            ban_user: 1 (Boolean)
            unban_user: 1 (Boolean)

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#0001",
                "profile_photo": "profiles_photos\/wECun9eXzdS3YSu79PbPE9waMQ5xt04HhSPzRniy.jpg",
                "background_photo": "backgrounds_photos\/TGM7T4bOnO5StxkGVeY95yJp6L6oAqS2FCcv0K3I.jpg",
                "about": "um animal burro desprovido da inteligencia",
                "banned": true,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": true,
                "update_manga": true,
                "delete_manga": true,
                "upload_manga_chapter": true,
                "update_manga_chapter": true,
                "delete_manga_chapter": true,
                "create_novel": true,
                "update_novel": true,
                "delete_novel": true,
                "upload_novel_chapter": true,
                "update_novel_chapter": true,
                "delete_novel_chapter": true,
                "create_people": true,
                "update_people": true,
                "delete_people": true,
                "ban_user": true,
                "unban_user": true,
                "manager_permisions": true,
                "owner": false,
                "created_at": "2022-03-13T20:04:20.000000Z",
                "updated_at": "2022-03-20T00:38:41.000000Z"
            }

+ Response 403

## admin permisions [/api/admin/managerpermisions/{id}]

### Admin permisions [POST]

(owner requerid)

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

    + Body

            manager_permisions: 1 (Boolean requerid)

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Galho#0001",
                "profile_photo": "profiles_photos\/wECun9eXzdS3YSu79PbPE9waMQ5xt04HhSPzRniy.jpg",
                "background_photo": "backgrounds_photos\/TGM7T4bOnO5StxkGVeY95yJp6L6oAqS2FCcv0K3I.jpg",
                "about": "um animal burro desprovido da inteligencia",
                "banned": true,
                "message": true,
                "report_message": true,
                "report_chapter": true,
                "create_manga": true,
                "update_manga": true,
                "delete_manga": true,
                "upload_manga_chapter": true,
                "update_manga_chapter": true,
                "delete_manga_chapter": true,
                "create_novel": true,
                "update_novel": true,
                "delete_novel": true,
                "upload_novel_chapter": true,
                "update_novel_chapter": true,
                "delete_novel_chapter": true,
                "create_people": true,
                "update_people": true,
                "delete_people": true,
                "ban_user": true,
                "unban_user": true,
                "manager_permisions": false,
                "owner": true,
                "created_at": "2022-03-13T20:04:20.000000Z",
                "updated_at": "2022-03-20T01:03:26.000000Z"
            }

+ Response 403

# Group People

## People infos [/api/people/{id}]

### People get [GET]

+ Parameters

    + id: `2` (integer) token id

+ Response 200 (application/json)

    + Body

            {
                "id": 2,
                "photo": "people_photo\/HOB1RMniBM5S6xcECWEApphcHzisyCfuGf0TZNp0.jpg",
                "name": "macaco",
                "birth": "2022-03-19",
                "gender": "Desconhecido",
                "about": "Nada",
                "twitter": null,
                "facebook": null,
                "instagram": null,
                "anilist": null,
                "myanimelist": null,
                "youtube": null,
                "website": null,
                "created_at": "2022-03-20T02:45:28.000000Z",
                "updated_at": "2022-03-20T21:00:06.000000Z"
            }

+ Response 404

### Create people [POST]

(create_people requerid or owner)

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA
            Accept: application/json

    + Body

            name: "Oda" (string unique requerid)
            photo: image (image)
            birth: 03/10/2022 (data)
            gender: "male" (string)
            about: "Eiichiro Oda é um mangaká, sendo mais conhecido como criador da série One Piece. One Piece é o Mangá mais vendido de todos os tempos com 480 milhões de cópias vendidas em todo o mundo, rendendo à Oda o título de um dos autores de ficção" (string min:20 max:300)
            twitter: "twitter.com" (string)
            facebook: "facebook.com" (string)
            instagram: "instagram.com" (string)
            anilist: "anilist.com" (string)
            myanimelist: "myanimelist.com" (string)
            youtube: "youtube.com" (string)
            website: "websiteexemple.com" (string)

+ Response 200 (application/json)

    + Body

            {
                "id": 5,
                "photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "name": "Oda",
                "birth": "2022-03-19",
                "gender": "Desconhecido",
                "about": "Nada",
                "twitter": null,
                "facebook": null,
                "instagram": null,
                "anilist": null,
                "myanimelist": null,
                "youtube": null,
                "website": null,
                "created_at": "2022-03-20T02:52:36.000000Z",
                "updated_at": "2022-03-20T02:52:36.000000Z"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The name has already been taken.",
                "errors": {
                    "name": [
                        "The name has already been taken."
                    ]
                }
            }

+ Response 403

### delete people [DELETE]

(delete_people requerid or owner)

+ Parameters

    + id: `2` (integer) token id

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA

+ Response 200

+ Response 403

+ Response 404

## People infos2 [/api/people/update/{id}]

### update people [POST]

(update_people requerid or owner)

+ Parameters

    + id: `2` (integer) token id

+ Request

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA
            Accept: application/json

    + Body

            name: "Oda" (string unique)
            photo: image (image)
            birth: 03/10/2022 (data)
            gender: "male" (string)
            about: "Eiichiro Oda é um mangaká, sendo mais conhecido como criador da série One Piece. One Piece é o Mangá mais vendido de todos os tempos com 480 milhões de cópias vendidas em todo o mundo, rendendo à Oda o título de um dos autores de ficção" (string min:20 max:300)
            twitter: "twitter.com" (string)
            facebook: "facebook.com" (string)
            instagram: "instagram.com" (string)
            anilist: "anilist.com" (string)
            myanimelist: "myanimelist.com" (string)
            youtube: "youtube.com" (string)
            website: "websiteexemple.com" (string)

+ Response 200 (application/json)

    + Body

            {
                "id": 5,
                "photo": "http:\/\/localhost:8000\/imgs\/profile.avif",
                "name": "Oda",
                "birth": "2022-03-19",
                "gender": "Desconhecido",
                "about": "Nada",
                "twitter": null,
                "facebook": null,
                "instagram": null,
                "anilist": null,
                "myanimelist": null,
                "youtube": null,
                "website": null,
                "created_at": "2022-03-20T02:52:36.000000Z",
                "updated_at": "2022-03-20T02:52:36.000000Z"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The name has already been taken.",
                "errors": {
                    "name": [
                        "The name has already been taken."
                    ]
                }
            }

+ Response 403

# Group Category

## Category infos [/category/{id}]

### Create category [POST]

(create_category requerid or owner)

+ Request (application/json)

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA
            Accept: application/json

    + Body

            {
                "name": "Romance"
            }

+ Response 200 (application/json)

    + Body

            {
                "name": "Ação",
                "updated_at": "2022-03-20T22:11:16.000000Z",
                "created_at": "2022-03-20T22:11:16.000000Z",
                "id": 2
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The name must not be greater than 32 characters.",
                "errors": {
                    "name": [
                        "The name must not be greater than 32 characters."
                    ]
                }
            }

+ Response 403

### Update category [PUT]

(update_category requerid or owner)

+ Parameters

    + id: `2` (integer) token id

+ Request (application/json)

    + Headers

            Authentication: Bearer 2|fjxke44dxBeyNPE5twNnzrMO4BfWgCpSudH7WYEA
            Accept: application/json

    + Body

            {
                "name": "Romance"
            }

+ Response 200 (application/json)

    + Body

            {
                "name": "Ação",
                "updated_at": "2022-03-20T22:11:16.000000Z",
                "created_at": "2022-03-20T22:11:16.000000Z",
                "id": 2
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "The name must not be greater than 32 characters.",
                "errors": {
                    "name": [
                        "The name must not be greater than 32 characters."
                    ]
                }
            }

+ Response 403

### Update category [DELETE]

(delete_category requerid or owner)

+ Parameters

    + id: `2` (integer) token id

+ Response 200

+ Response 403

+ Response 404

# Group Search
