version: "3.3"
services:
    db:
        image: postgres:14.1-alpine
        container_name: postgres-tekkadan
        ports:
          - "3306:5432"
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
